### ISSUE TITLE
Population As Atomspace

### ISSUE THREAD

**Issue by behailu04** [singnet/as-moses#14]
### Implementation Plan 
I opened this issue to discuss on the implementation of storing deme populations on AtomSpace. For simplicity as suggested #11  to locate such AtomSpace within the fitness
function itself, more specifically in atomese_based_scorer. So the
steps would be : 
- [ ] Add AtomSpace member to `atomese_based_scorer`
- [ ] In `atomese_based__scorer::operator()` , before evaluating the program via calling `_cscorer.get_cscore(handle)` , add it in the atomspace.
- [ ] A MOSES flag (documented in `moses --hlep` ) should be added to enable or disable storing programs in the atomspace of `atomese_based_scorer` , to easily compare the benefits vs costs of storing candidates in an atomspace.
